-- 签到活动建表脚本
-- 执行说明：
-- 1. 本脚本只创建签到活动新增表，不修改 activity 主表；activity_type=8 由代码枚举维护。
-- 2. 签到流水、奖励发放记录按手机号尾数分 10 张表：0~9。
-- 3. MySQL 8 / InnoDB / utf8mb4。

CREATE TABLE IF NOT EXISTS `activity_sign` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `activity_cover_image` varchar(500) DEFAULT NULL COMMENT '活动封面图',
  `activity_background_image` varchar(500) DEFAULT NULL COMMENT '活动背景图',
  `unsigned_image` varchar(500) DEFAULT NULL COMMENT '未签到图',
  `signed_image` varchar(500) DEFAULT NULL COMMENT '已签到图',
  `activity_detail_image` varchar(500) DEFAULT NULL COMMENT '活动详情长图',
  `theme_color` varchar(32) DEFAULT NULL COMMENT '主题颜色/颜色选择器值',
  `share_type` tinyint DEFAULT 2 COMMENT '分享方式：1不允许转发 2允许转发好友 3允许复制链接',
  `share_title` varchar(255) DEFAULT NULL COMMENT '分享标题',
  `share_note` varchar(255) DEFAULT NULL COMMENT '分享内容',
  `share_img_url` varchar(500) DEFAULT NULL COMMENT '分享图片',
  `reset_enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否开启周期及奖励重置：0否 1是',
  `reset_type` tinyint DEFAULT NULL COMMENT '重置类型：1按周 2按月',
  `reset_days` varchar(128) DEFAULT NULL COMMENT '重置日期配置：reset_type=1按周时存1~7，1周一...7周日；reset_type=2按月时存1~31，32月末；逗号分隔，29/30/31遇小月按月末处理',
  `continuous_cycle_days` int DEFAULT NULL COMMENT '连签周期：1~365整数，用于统计用户满足连签周期的次数',
  `community_only` tinyint DEFAULT 0 COMMENT '社群专享：0否 1是',
  `store_manager_qr_code_guide_image` varchar(500) DEFAULT NULL COMMENT '店长企微码引导图',
  `store_group_qr_code_guide_image` varchar(500) DEFAULT NULL COMMENT '门店群活码引导图',
  `activity_rule` text DEFAULT NULL COMMENT '活动规则，富文本',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_id` (`activity_id`),
  KEY `idx_activity_reset` (`activity_id`, `reset_enabled`, `reset_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动配置表';

CREATE TABLE IF NOT EXISTS `activity_sign_reward` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_type` int(1) NOT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_id` bigint DEFAULT NULL COMMENT '奖品业务ID，如券ID、券包ID、实物ID；积分/红包可为空',
  `prize_content` varchar(500) NOT NULL COMMENT '奖品内容/奖励名称，对齐抽签活动prize_content',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `sign_days` int DEFAULT NULL COMMENT '连续/累计天数；每日签到可为空',
  `grant_mode` tinyint NOT NULL DEFAULT 1 COMMENT '发放方式：1当日发放 2次日发放，第一期主要使用1',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  KEY `idx_activity_create` (`activity_id`, `create_time`, `id`),
  KEY `idx_activity_rule` (`activity_id`, `sign_rule_type`, `sign_days`),
  KEY `idx_activity_prize_type` (`activity_id`, `prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励表';


CREATE TABLE IF NOT EXISTS `activity_sign_record_0` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_0';


CREATE TABLE IF NOT EXISTS `activity_sign_record_1` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_1';


CREATE TABLE IF NOT EXISTS `activity_sign_record_2` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_2';


CREATE TABLE IF NOT EXISTS `activity_sign_record_3` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_3';


CREATE TABLE IF NOT EXISTS `activity_sign_record_4` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_4';


CREATE TABLE IF NOT EXISTS `activity_sign_record_5` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_5';


CREATE TABLE IF NOT EXISTS `activity_sign_record_6` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_6';


CREATE TABLE IF NOT EXISTS `activity_sign_record_7` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_7';


CREATE TABLE IF NOT EXISTS `activity_sign_record_8` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_8';


CREATE TABLE IF NOT EXISTS `activity_sign_record_9` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，签到权益维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `trigger_member_id` bigint NOT NULL COMMENT '本次触发签到的会员ID；同手机号多memberId时，签到判重按手机号，奖励发给当前memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint DEFAULT NULL COMMENT '签到门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `sign_date` date NOT NULL COMMENT '签到日期',
  `sign_time` datetime NOT NULL COMMENT '签到时间',
  `sign_type` tinyint NOT NULL DEFAULT 1 COMMENT '签到类型：1正常签到 2补签 3后台补录；本期只用1',
  `continuous_days_after` int NOT NULL DEFAULT 0 COMMENT '本次签到后连续签到天数',
  `total_days_after` int NOT NULL DEFAULT 0 COMMENT '本周期累计签到天数',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_mobile_date` (`activity_id`, `member_mobile`, `sign_date`),
  KEY `idx_activity_period_date` (`activity_id`, `period_key`, `sign_date`),
  KEY `idx_mobile_activity` (`member_mobile`, `activity_id`),
  KEY `idx_activity_member_time` (`activity_id`, `member_mobile`, `sign_time`),
  KEY `idx_activity_store_time` (`activity_id`, `store_id`, `sign_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动签到流水表_9';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_0` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_0';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_1` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_1';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_2` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_2';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_3` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_3';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_4` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_4';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_5` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_5';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_6` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_6';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_7` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_7';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_8` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_8';


CREATE TABLE IF NOT EXISTS `activity_sign_reward_record_9` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `activity_id` bigint NOT NULL COMMENT '活动ID',
  `prize_id` bigint NOT NULL COMMENT '奖品ID/签到奖励配置ID',
  `member_mobile` varchar(50) NOT NULL COMMENT '手机号，奖励达成维度',
  `mobile_shard` tinyint NOT NULL COMMENT '手机号尾数分片：0~9',
  `member_id` bigint NOT NULL COMMENT '会员ID，实际发放给的memberId',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称',
  `gender` tinyint(1) DEFAULT NULL COMMENT '性别：0保密 1男 2女',
  `member_category` tinyint DEFAULT NULL COMMENT '用户类别：0微信 1支付宝',
  `store_id` bigint DEFAULT NULL COMMENT '参与门店ID，当前活动该用户第一次签到门店',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称，当前活动该用户第一次签到门店名称',
  `period_key` varchar(64) NOT NULL COMMENT '签到周期标识，仅后端内部使用',
  `period_start_time` datetime NOT NULL COMMENT '签到周期开始时间',
  `period_end_time` datetime NOT NULL COMMENT '签到周期结束时间',
  `reset_enabled_snapshot` tinyint DEFAULT NULL COMMENT '当时重置开关快照：0否 1是',
  `reset_type_snapshot` tinyint DEFAULT NULL COMMENT '当时重置类型快照：1按周 2按月',
  `reset_days_snapshot` varchar(128) DEFAULT NULL COMMENT '当时重置日期配置快照',
  `reward_rule_snapshot` varchar(500) DEFAULT NULL COMMENT '当时奖励规则快照',
  `prize_type` int(1) DEFAULT NULL COMMENT '奖品类型，复用ActivityCqPrizeTypeEnum：1优惠券 2积分 3实物 5现金红包 6优惠券包',
  `prize_content` varchar(500) DEFAULT NULL COMMENT '奖品内容',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(18,4) DEFAULT NULL COMMENT '奖品值：积分数/红包金额等，红包保留4位小数',
  `sign_rule_type` tinyint NOT NULL COMMENT '签到规则：1每日签到 2连续签到 3累计签到',
  `trigger_days` int DEFAULT NULL COMMENT '触发天数：连续/累计奖励存配置天数，每日奖励可为空',
  `sign_date` date DEFAULT NULL COMMENT '每日签到奖励去重日期',
  `sign_record_id` bigint DEFAULT NULL COMMENT '触发奖励的签到流水ID',
  `grant_key` varchar(200) NOT NULL COMMENT '奖励发放幂等key',
  `issue_status` tinyint NOT NULL DEFAULT 0 COMMENT '发放状态：0待发放 1发放中 2已发放 3发放失败',
  `issue_time` datetime DEFAULT NULL COMMENT '发放成功/发放完成时间',
  `fail_reason` varchar(500) DEFAULT NULL COMMENT '发放失败原因',
  `external_record_id` varchar(100) DEFAULT NULL COMMENT '外部发放记录ID',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态：0已发放 1未填写收货地址 2已填写地址待发货 3已发货 9已退回',
  `receive_user` varchar(255) DEFAULT NULL COMMENT '收件人',
  `receive_mobile` varchar(50) DEFAULT NULL COMMENT '收件联系方式',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收件地址',
  `tracking_number` varchar(255) DEFAULT NULL COMMENT '快递单号',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '商户转账单号/红包外部单号',
  `claim_status` int(1) DEFAULT 1 COMMENT '红包领取状态：1未领取 2已领取 3已过期/已失效',
  `package_info` varchar(500) DEFAULT NULL COMMENT '红包返参链接/领取链接',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updater` varchar(64) DEFAULT NULL COMMENT '更新人',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
  `business_id` bigint DEFAULT NULL COMMENT '项目ID/业务ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_grant_key` (`grant_key`),
  KEY `idx_activity_period` (`activity_id`, `period_key`),
  KEY `idx_activity_mobile` (`activity_id`, `member_mobile`),
  KEY `idx_activity_status` (`activity_id`, `issue_status`),
  KEY `idx_activity_prize_type_time` (`activity_id`, `prize_type`, `create_time`),
  KEY `idx_activity_issue_time` (`activity_id`, `issue_time`),
  KEY `idx_cover_query` (`out_bill_no`, `prize_type`, `id`, `update_time`),
  KEY `idx_prize_type` (`prize_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='签到活动奖励发放记录表_9';
