-- 有奖问答完整建表脚本
-- 说明：
-- 1. 本脚本会先删除有奖问答相关业务表，再重新创建，适合测试环境初始化或全量重建。
-- 2. 活动名称、活动规则、启用状态、开始结束日期、指定日期、指定周几、场次时间段复用 activity 主表。
-- 3. 活动门店范围复用 activity_store，渠道推广复用 activity_channel。
-- 4. 题目现阶段只支持选择题，答案只保存选项编码；导出时通过明细表判断每题对错。

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `activity_answer_reward_log`;
DROP TABLE IF EXISTS `activity_answer_task`;
DROP TABLE IF EXISTS `activity_answer_record_detail`;
DROP TABLE IF EXISTS `activity_answer_record`;
DROP TABLE IF EXISTS `activity_answer_commodity`;
DROP TABLE IF EXISTS `activity_answer_reward`;
DROP TABLE IF EXISTS `activity_answer_question`;
DROP TABLE IF EXISTS `activity_answer`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `activity_answer` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `activity_store` tinyint(1) NOT NULL DEFAULT '0' COMMENT '活动门店范围 0指定门店 1全部门店',
  `activity_img_url` varchar(500) DEFAULT NULL COMMENT '活动封面图',
  `activity_background` varchar(500) DEFAULT NULL COMMENT '活动背景图',
  `button_img_url` varchar(500) DEFAULT NULL COMMENT '开始答题按钮图',
  `activity_detail_long_image` varchar(500) DEFAULT NULL COMMENT '活动详情长图，可不传',
  `question_background_image` varchar(500) DEFAULT NULL COMMENT '答题页面背景图',
  `unselected_option_image` varchar(500) DEFAULT NULL COMMENT '未选择选项图',
  `selected_option_image` varchar(500) DEFAULT NULL COMMENT '已选择选项图',
  `previous_button_image` varchar(500) DEFAULT NULL COMMENT '上一题按钮图',
  `next_button_image` varchar(500) DEFAULT NULL COMMENT '下一题按钮图',
  `submit_button_image` varchar(500) DEFAULT NULL COMMENT '确认提交按钮图',
  `background_color` varchar(64) DEFAULT NULL COMMENT '页面背景颜色',
  `share_title` varchar(255) DEFAULT NULL COMMENT '分享标题',
  `share_note` varchar(255) DEFAULT NULL COMMENT '分享内容',
  `share_img_url` varchar(500) DEFAULT NULL COMMENT '分享图片',
  `share_type` int(11) DEFAULT '2' COMMENT '分享类型 1不允许转发好友 2允许转发好友 3允许复制链接',
  `public_button` int(1) DEFAULT '0' COMMENT '公共展示 0开启 1关闭',
  `community_flag` int(1) NOT NULL DEFAULT '1' COMMENT '社群专享 1不开启 2开启',
  `guide_image` text COMMENT '引导图片',
  `answer_total_number` int(11) DEFAULT '0' COMMENT '答题总次数 0不限制，其余为活动期间每人最多答题次数',
  `calculation_rules` int(1) DEFAULT '1' COMMENT '次数计算规则 1按天计算 2按场次计算',
  `prize_pool_rules` int(1) DEFAULT '1' COMMENT '门店奖励库存规则 1共用库存 2独立库存',
  `answer_rules_reset` int(1) DEFAULT '0' COMMENT '奖励及答题规则重置 0关闭 1开启',
  `free_status` int(1) NOT NULL DEFAULT '0' COMMENT '免费获得 0关闭 1开启',
  `free_count` int(11) DEFAULT NULL COMMENT '免费获得答题次数',
  `sign_status` int(1) NOT NULL DEFAULT '0' COMMENT '签到获得 0关闭 1开启',
  `sign_count` int(11) DEFAULT NULL COMMENT '签到获得答题次数',
  `points_status` int(1) NOT NULL DEFAULT '0' COMMENT '积分获得 0关闭 1开启',
  `points_type` int(1) DEFAULT NULL COMMENT '积分限制类型 0每人每天 1不限制',
  `points_count` int(11) DEFAULT NULL COMMENT '积分限制次数',
  `order_status` int(1) NOT NULL DEFAULT '0' COMMENT '下单获得 0关闭 1开启',
  `place_order_type` int(1) DEFAULT '2' COMMENT '下单类型 1按品类限制 2按商品限制',
  `category_type` int(1) DEFAULT NULL COMMENT '参与品类 1全部 2仅单品 3仅套餐',
  `place_order_product` int(1) DEFAULT NULL COMMENT '下单商品 1全部商品 2指定商品',
  `payment_type` int(1) DEFAULT NULL COMMENT '支付门槛 0不限制 1限制',
  `payment_count` decimal(11,2) DEFAULT NULL COMMENT '支付金额门槛',
  `place_order_answer` int(1) DEFAULT NULL COMMENT '下单答题次数限制类型 0每人每天 1不限制',
  `place_order_answer_number` int(11) DEFAULT NULL COMMENT '下单可获得答题次数',
  `share_event` int(1) NOT NULL DEFAULT '0' COMMENT '分享活动 0关闭 1开启',
  `share_count` int(11) DEFAULT NULL COMMENT '分享获得答题次数',
  `browse_type` int(1) DEFAULT '0' COMMENT '浏览首页 0关闭 1开启',
  `browse_count` int(11) DEFAULT NULL COMMENT '浏览首页获得答题次数',
  `create_user_name` varchar(100) DEFAULT NULL COMMENT '创建人姓名',
  `update_user_name` varchar(100) DEFAULT NULL COMMENT '修改人姓名',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_id` (`activity_id`),
  KEY `idx_activity_store` (`activity_store`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答活动配置表';

CREATE TABLE `activity_answer_question` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `question_type` int(1) NOT NULL DEFAULT '1' COMMENT '题目类型 1选择题',
  `question_title` varchar(2000) NOT NULL COMMENT '题目名称',
  `question_tips` varchar(500) DEFAULT NULL COMMENT '题目提示文案',
  `options_json` varchar(2000) NOT NULL COMMENT '选项JSON',
  `correct_answer` varchar(20) NOT NULL COMMENT '正确答案选项编码',
  `answer_time` int(11) DEFAULT '0' COMMENT '每题答题时间，单位秒，0不限制',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  KEY `idx_activity_id` (`activity_id`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答题目表';

CREATE TABLE `activity_answer_reward` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `correct_count` int(11) NOT NULL COMMENT '答对数量档位',
  `prize_type` int(1) NOT NULL COMMENT '奖品类型 1积分 2优惠券 3优惠券包 4实物奖品 5现金红包',
  `award_id` bigint(20) DEFAULT NULL COMMENT '奖品ID，根据类型判断是优惠券ID还是商品ID',
  `code` varchar(255) DEFAULT NULL COMMENT '编码',
  `coupon_name` varchar(255) DEFAULT NULL COMMENT '优惠券名称',
  `prize_name` varchar(255) DEFAULT NULL COMMENT '奖品名称快照',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片快照',
  `prize_value` decimal(10,2) DEFAULT NULL COMMENT '奖品价值快照',
  `total_num` int(11) NOT NULL DEFAULT '0' COMMENT '总库存 0不限库存',
  `used_num` int(11) NOT NULL DEFAULT '0' COMMENT '已发库存',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_correct` (`activity_id`, `correct_count`),
  KEY `idx_prize` (`prize_type`, `award_id`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答奖励档位表';

CREATE TABLE `activity_answer_record` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `answer_no` varchar(64) NOT NULL COMMENT '答题编号',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `member_id` bigint(20) NOT NULL COMMENT '会员ID',
  `member_mobile` bigint(20) NOT NULL COMMENT '会员手机号快照',
  `period_key` varchar(64) NOT NULL COMMENT '活动场次/周期标识',
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `store_id` bigint(20) DEFAULT NULL COMMENT '参与门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称快照',
  `question_count` int(11) DEFAULT '0' COMMENT '题目数量',
  `correct_count` int(11) DEFAULT '0' COMMENT '正确数量',
  `wrong_count` int(11) DEFAULT '0' COMMENT '错误数量',
  `accuracy` decimal(5,2) DEFAULT '0.00' COMMENT '正确率',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '答题状态 0未完成 1已完成',
  `cancel_status` int(1) NOT NULL DEFAULT '0' COMMENT '取消状态 0未取消 1已取消',
  `start_time` datetime DEFAULT NULL COMMENT '开始答题时间',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_answer_no` (`answer_no`),
  KEY `idx_activity_mobile_period` (`activity_id`, `member_mobile`, `period_key`),
  KEY `idx_record_filter` (`activity_id`, `store_id`, `status`, `start_time`),
  KEY `idx_record_mobile` (`activity_id`, `member_mobile`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答答题记录表';

CREATE TABLE `activity_answer_record_detail` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `record_id` bigint(20) NOT NULL COMMENT '答题记录ID',
  `member_id` bigint(20) NOT NULL COMMENT '会员ID',
  `member_mobile` bigint(20) NOT NULL COMMENT '会员手机号快照',
  `question_id` bigint(20) NOT NULL COMMENT '题目ID',
  `selected_answer` varchar(20) DEFAULT NULL COMMENT '用户选择的选项编码',
  `answer_result` int(1) NOT NULL DEFAULT '0' COMMENT '作答结果 0错误 1正确',
  `answer_time` bigint(20) DEFAULT NULL COMMENT '本题用时，单位秒',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_question` (`record_id`, `question_id`),
  KEY `idx_activity_id` (`activity_id`),
  KEY `idx_question_id` (`question_id`),
  KEY `idx_answer_result` (`answer_result`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答答题明细表';

CREATE TABLE `activity_answer_task` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动ID',
  `member_id` bigint(20) DEFAULT NULL COMMENT '会员ID',
  `member_mobile` bigint(20) NOT NULL COMMENT '会员手机号快照',
  `task_type` int(1) NOT NULL COMMENT '任务类型 3下单 4分享 5浏览首页 6签到',
  `period_key` varchar(64) NOT NULL COMMENT '活动场次/次数周期标识',
  `task_date` date DEFAULT NULL COMMENT '任务日期',
  `finish_count` int(11) NOT NULL DEFAULT '0' COMMENT '完成次数',
  `gain_count` int(11) NOT NULL DEFAULT '0' COMMENT '获得答题次数',
  `consume_count` int(11) NOT NULL DEFAULT '0' COMMENT '消耗答题次数',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_answer_task_period` (`activity_id`, `member_mobile`, `task_type`, `period_key`),
  KEY `idx_answer_task_member` (`activity_id`, `member_mobile`),
  KEY `idx_answer_task_date` (`activity_id`, `task_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答任务记录表';

CREATE TABLE `activity_answer_reward_log` (
  `member_name` varchar(255) DEFAULT NULL COMMENT '会员昵称快照',
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `record_id` bigint(20) NOT NULL COMMENT '答题记录ID',
  `answer_no` varchar(64) DEFAULT NULL COMMENT '答题编号',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `member_id` bigint(20) NOT NULL COMMENT '会员ID',
  `member_mobile` bigint(20) NOT NULL COMMENT '会员手机号快照',
  `store_id` bigint(20) DEFAULT NULL COMMENT '参与门店ID',
  `store_name` varchar(255) DEFAULT NULL COMMENT '参与门店名称',
  `reward_id` bigint(20) DEFAULT NULL COMMENT '命中奖励档位ID',
  `reward_correct_count` int(11) DEFAULT NULL COMMENT '实际命中奖励档位答对题数',
  `prize_type` int(1) NOT NULL COMMENT '奖品类型 1积分 2优惠券 3优惠券包 4实物奖品 5现金红包',
  `prize_id` bigint(20) DEFAULT NULL COMMENT '奖品ID',
  `prize_name` varchar(255) DEFAULT NULL COMMENT '奖品名称快照',
  `prize_img_url` varchar(500) DEFAULT NULL COMMENT '奖品图片',
  `prize_value` decimal(10,2) DEFAULT NULL COMMENT '奖品价值',
  `claim_status` int(1) DEFAULT NULL COMMENT '红包领取状态 1未领取 2已领取 3已失效',
  `package_info` varchar(2000) DEFAULT NULL COMMENT '红包调起支付参数',
  `out_bill_no` varchar(64) DEFAULT NULL COMMENT '红包商户转账单号',
  `prize_state` int(1) DEFAULT NULL COMMENT '奖品状态 0已发放 1未填写地址 2待发货 3已发货 9退回',
  `receive_user` varchar(50) DEFAULT NULL COMMENT '收货人',
  `receive_mobile` varchar(20) DEFAULT NULL COMMENT '收货手机号',
  `receive_address` varchar(500) DEFAULT NULL COMMENT '收货地址',
  `express_company` varchar(100) DEFAULT NULL COMMENT '快递公司',
  `tracking_number` varchar(100) DEFAULT NULL COMMENT '快递单号',
  `grant_time` datetime DEFAULT NULL COMMENT '发放时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_id` (`record_id`),
  KEY `idx_activity_id` (`activity_id`),
  KEY `idx_activity_reward` (`activity_id`, `reward_id`),
  KEY `idx_activity_reward_store` (`activity_id`, `reward_id`, `store_id`),
  KEY `idx_member_mobile` (`member_mobile`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_prize_type` (`prize_type`),
  KEY `idx_grant_time` (`grant_time`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答奖励发放记录表';

CREATE TABLE `activity_answer_commodity` (
  `id` bigint(20) NOT NULL COMMENT '主键ID',
  `activity_id` bigint(20) NOT NULL COMMENT '活动主表ID',
  `commodity_id` bigint(20) NOT NULL COMMENT '指定商品ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户编号',
  `business_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '项目ID',
  PRIMARY KEY (`id`),
  KEY `idx_activity_id` (`activity_id`),
  KEY `idx_commodity_id` (`commodity_id`),
  KEY `idx_business_id` (`business_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='有奖问答下单任务商品范围表';
