-- 1. 巡店记录主表 (记录每一次巡店任务的整体情况)
CREATE TABLE `system_store_inspection_record` (
  `id` bigint(20) NOT NULL COMMENT '巡店记录ID',
  `store_id` bigint(20) NOT NULL COMMENT '门店ID',
  `store_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '门店名称(快照)',
  `template_id` bigint(20) NOT NULL COMMENT '使用的模板ID',
  `template_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '模板名称(快照)',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态：0 进行中, 1 已完成, 2 已失效',
  `inspector_id` bigint(20) DEFAULT NULL COMMENT '巡店人ID',
  `inspector_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '巡店人姓名',
  `inspector_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '巡店人电话',
  `in_scope` tinyint(1) DEFAULT NULL COMMENT '是否在范围内 0在 1不在',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '理论结束时间 = 开始时间+1天',
  `store_pic` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '门头照',
  `total_score` int(5) DEFAULT '0' COMMENT '模板预设满分',
  `actual_score` int(5) DEFAULT '0' COMMENT '实际得分',
  `score_rate` decimal(5,2) DEFAULT '0.00' COMMENT '得分率',
  `item_count` int(5) DEFAULT '0' COMMENT '点检项目总数',
  `qualified_count` int(5) DEFAULT '0' COMMENT '合格数',
  `unqualified_count` int(5) DEFAULT '0' COMMENT '不合格数',
  `not_applicable_count` int(5) DEFAULT '0' COMMENT '不适用数',
  `creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
  `over_time` datetime DEFAULT NULL COMMENT '结束时间',
  `reward_amount` decimal(10,2) DEFAULT '0.00' COMMENT '奖惩金额',
  `store_patrol_position` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '巡店定位',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡店记录主表';

CREATE TABLE `system_store_inspection_record_item` (
   `id` bigint(20) NOT NULL COMMENT '记录明细ID',
   `record_id` bigint(20) NOT NULL COMMENT '所属巡店记录ID',
   `type_id` bigint(20) NOT NULL COMMENT '检点项目大类id',
   `type_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '检点项目大类名称',
   `checklist_id` bigint(20) NOT NULL COMMENT '关联原始点检项ID',
   `title_snap` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题快照',
   `prompt_snap` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示快照',
   `standard_snap` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '点检标准快照',
   `max_score_snap` int(3) DEFAULT NULL COMMENT '该项满分快照',
   `img_state_snap` tinyint(1) DEFAULT NULL COMMENT '图片上传规则快照 0 不必传 1 合格时必传 2 不合格时必传 3 不适用时必传',
   `img_count_snap` int(2) DEFAULT NULL COMMENT '应传图片数量快照',
   `actual_status` tinyint(1) DEFAULT '3' COMMENT '检查结果：0 不合格, 1 合格, 2 不适用,3 没批',
   `actual_score` int(3) DEFAULT '0' COMMENT '实际得分',
   `reward_amount` decimal(10,2) DEFAULT '0.00' COMMENT '奖惩金额',
   `actual_comment` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '巡店人备注',
   `actual_images` text COLLATE utf8mb4_unicode_ci COMMENT '图片地址(多图用逗号或JSON数组存储)',
   `is_rectified` tinyint(1) DEFAULT '0' COMMENT '是否已整改：0 否, 1 是',
   `rectify_time` datetime DEFAULT NULL COMMENT '整改完成时间',
   `creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
   `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
   `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
   `img_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片规则\r\n{\r\n"imgFlag":"0 不允许上传 1 允许上传",\r\n"imgState":"0 不必传 1 合格时必传 2 不合格时必传 3 不适用时必传",\r\n"imgCount":"1",\r\n"localImgFlag":"0 不允许本地上传 1 允许本地上传"\r\n}',
   `description_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '描述规则\r\n{\r\n"descriptionFlag":"0 不允许填写 1 允许填写",\r\n"qualified":"0 选填 1 必填",\r\n"unqualified":"0 选填 1 必填",\r\n"inapplicability":"0 选填 1 必填"\r\n}',
   `inapplicability_rule` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '不适用规则\r\n{\r\n"showFlag":"0 不显示 1显示"\r\n}',
   `reward_punishment_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '奖惩规则\r\n{\r\n"rewardPunishmentFlag":"0 不填 1填写",\r\n"qualified":"0 选填 1 必填",\r\n"unqualified":"0 选填 1 必填"\r\n}',
   `sort` tinyint(4) DEFAULT NULL COMMENT '排序',
   `business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
   `type_sort` tinyint(3) NOT NULL DEFAULT '0' COMMENT '大类排序',
   PRIMARY KEY (`id`) USING BTREE,
   KEY `idx_record_id` (`record_id`),
   KEY `idx_checklist_id` (`checklist_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡店记录明细快照表';

CREATE TABLE `system_store_inspection_item_log` (
    `id` bigint(20) NOT NULL COMMENT '日志ID',
    `business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
    `record_id` bigint(20) NOT NULL COMMENT '所属巡店记录ID',
    `record_item_id` bigint(20) NOT NULL COMMENT '所属巡店明细项ID',
    `operator_id` bigint(20) DEFAULT NULL COMMENT '操作人ID',
    `operator_name` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作人姓名',
    `operate_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
    `before_snap` json DEFAULT NULL COMMENT '变更前数据快照',
    `after_snap` json DEFAULT NULL COMMENT '变更后数据快照',
    `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '修改原因备注',
    `creator` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE,
    KEY `idx_record_item_id` (`record_item_id`),
    KEY `idx_record_id` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡店项操作变更日志表';


CREATE TABLE `system_store_inspection_type` (
`type_id` bigint(20) NOT NULL COMMENT '点检项目大类ID',
`type_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '名称',
`creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
`business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
PRIMARY KEY (`type_id`),
KEY `idx_inspection_type_name` (`type_name`,`business_id`,`deleted`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡店点检项目分类表';


CREATE TABLE `system_store_inspection_checklist` (
`checklist_id` bigint(20) NOT NULL COMMENT '主键ID',
`type_id` bigint(20) DEFAULT NULL COMMENT '大类ID',
`type_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '大类名称',
`title` varchar(600) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
`prompt` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示',
`score` int(3) DEFAULT NULL COMMENT '总分',
`img_flag` tinyint(1) DEFAULT NULL COMMENT '0 不允许上传 1 允许上传',
`img_state` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '0 不必传 1 合格时必传 2 不合格时必传 3 不适用时必传',
`img_count` int(2) DEFAULT NULL COMMENT '上传图片个数',
`rectifier_flag` tinyint(1) DEFAULT NULL COMMENT '0 不需要整改人 1 需要整改人',
`rectifier` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '整改人',
`approver_flag` tinyint(1) DEFAULT NULL COMMENT '0 不需要审核人 1 需要审核人',
`approver` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审核人',
`cc_person` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '抄送人',
`deadline` int(3) DEFAULT NULL COMMENT '整改有效期',
`validity_period` int(3) DEFAULT NULL COMMENT '申述有效期',
`rectify_img_flag` tinyint(1) DEFAULT NULL COMMENT '0 不需要上传整改图片 1 需要上传整改图片',
`real_flag` tinyint(1) DEFAULT NULL COMMENT '0 不允许实时拍照 1允许实时拍照',
`inspection_standard` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '点检标准',
`sort` int(3) NOT NULL COMMENT '排序',
`creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
`business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
PRIMARY KEY (`checklist_id`),
KEY `idx_checklist_type_title` (`type_id`,`title`,`business_id`,`deleted`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='点检项';

CREATE TABLE `system_store_inspection_template` (
`template_id` bigint(20) NOT NULL COMMENT '主键',
`template_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模板名称',
`visibility_type` tinyint(1) NOT NULL COMMENT '可见类型 0 全部可见 1 指定成员可见',
`creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
`business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
PRIMARY KEY (`template_id`),
KEY `idx_store_inspection_template_name` (`template_name`,`business_id`,`deleted`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='巡店模板';

CREATE TABLE `system_template_checklist` (
`template_checklist_id` bigint(20) NOT NULL COMMENT '模板点检项ID',
`template_id` bigint(20) DEFAULT NULL COMMENT '模板id',
`type_id` bigint(20) NOT NULL COMMENT '大类ID',
`type_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '大类名称',
`checklist_id` bigint(20) NOT NULL COMMENT '点检项ID',
`title` varchar(600) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '点检项名称',
`prompt` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '提示',
`score` int(3) NOT NULL COMMENT '总分',
`deadline` int(3) DEFAULT NULL COMMENT '整改有效期',
`img_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '图片规则\r\n{\r\n"imgFlag":"0 不允许上传 1 允许上传",\r\n"imgState":"0 不必传 1 合格时必传 2 不合格时必传 3 不适用时必传",\r\n"imgCount":"1",\r\n"localImgFlag":"0 不允许本地上传 1 允许本地上传"\r\n}',
`description_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '描述规则\r\n{\r\n"descriptionFlag":"0 不允许填写 1 允许填写",\r\n"qualified":"0 选填 1 必填",\r\n"unqualified":"0 选填 1 必填",\r\n"inapplicability":"0 选填 1 必填"\r\n}',
`inapplicability_rule` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '不适用规则\r\n{\r\n"showFlag":"0 不显示 1显示"\r\n}',
`reward_punishment_rule` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '奖惩规则\r\n{\r\n"rewardPunishmentFlag":"0 不填 1填写",\r\n"qualified":"0 选填 1 必填",\r\n"unqualified":"0 选填 1 必填"\r\n}',
`sort` int(3) NOT NULL COMMENT '排序',
`type_sort` int(3) DEFAULT NULL COMMENT '大类排序',
`creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
`business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
PRIMARY KEY (`template_checklist_id`),
KEY `idx_template_checklist_template_id` (`template_id`,`type_id`,`checklist_id`,`title`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模板点检项';

CREATE TABLE `system_template_visible_user` (
`visibility_id` bigint(20) NOT NULL COMMENT '主键',
`user_id` bigint(20) NOT NULL COMMENT '用户ID',
`user_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名称',
`template_id` bigint(20) NOT NULL COMMENT '模板ID',
`creator` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '创建者',
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
`updater` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
`deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
`business_id` bigint(20) DEFAULT NULL COMMENT '项目ID',
PRIMARY KEY (`visibility_id`),
KEY `idx_visible_user_template_id` (`template_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='模板可见成员';