--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic: # 多数据源配置
      datasource:
        sharding:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
          url: jdbc:shardingsphere:nacos:sharding.yaml?serverAddr=${spring.cloud.nacos.config.server-addr}&namespace=${spring.cloud.nacos.config.namespace}&username=${spring.cloud.nacos.config.username}&password=${CLOUD_MEMBER_LOCAL_EMBEDDED_PASSWORD:}
        shadow_sharding:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
          url: jdbc:shardingsphere:nacos:shadow_sharding.yaml?serverAddr=${spring.cloud.nacos.config.server-addr}&namespace=${spring.cloud.nacos.config.namespace}&username=${spring.cloud.nacos.config.username}&password=${CLOUD_MEMBER_LOCAL_EMBEDDED_PASSWORD:}
  elasticsearch:
    repositories:
      enabled: true
    uris: "http://192.168.31.141:9200"
    # uris: "https://es-cn-rno438wed0006j382.elasticsearch.aliyuncs.com:9200" 生产
    socket-timeout: "60s"
    username: "elastic"
    password: ${CLOUD_MEMBER_LOCAL_PASSWORD_L21:}

--- #################### 用户手机号换绑次数上限 ####################
bindingMax: 5
--- #################### 用户手机号换绑次数上限 ####################

geocoder-key:
  # false：腾讯旧接口；true：迈云新接口
  maiyun-enabled: false
  maiyun-key: CLOUD_SECRET_REQUIRED
  maiyun-from: 3
  config:
    10: FPIBZ-DYJCU-BKLV6-GZMYQ-SWCFE-CCBDP
    9: CLOUD_SECRET_REQUIRED
    7: 6UZBZ-O5A6C-KS62R-A5VEJ-N4RA6-5YFJZ
    2: 6UZBZ-O5A6C-KS62R-A5VEJ-N4RA6-5YFJZ
    13: 6UZBZ-O5A6C-KS62R-A5VEJ-N4RA6-5YFJZ


--- #################### youdao相关配置 ####################
youdao:
  info:
    base-package: com.htyoudao.youdao.module.member
  swagger:
    title: 管理后台
    description: 提供会员管理的所有功能
    version: ${youdao.info.version}

wechat:
  token:
    url: http://wechat.htyoudao.com/prod-api/token
    auth: "Bearer 00905b52160dd2ed4c799639f0e06add1f7a"
  schemeInfo:
    envVersion: release
  apps: "{
    '9':{'appId':'wxbcaed25cd85609ab','appSecret':'CLOUD_SECRET_REQUIRED'},
    '10':{'appId':'wx3b84773f5f12d87f','appSecret':'CLOUD_SECRET_REQUIRED'},
    '7':{'appId':'wx9135e93470a0afdb','appSecret':'04b3cf8ebdb3db55554b1cf5e788d55b'},
    '2':{'appId':'wx0b670f3436a8dbbf','appSecret':'CLOUD_SECRET_REQUIRED'},
    '13':{'appId':'wx7b424bf5c2695da7','appSecret':'CLOUD_SECRET_REQUIRED'}
    }"

zfb:
  syncUrl: https://openapi.alipay.com/gateway.do
  apps: "{
    '100':{'appId':'2021004145680917',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L67:}
    'alipayPublicKey':'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},

    '10':{'appId':'2021006154675873',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L73:}
    'alipayPublicKey':'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},

    '9':{'appId':'2021004160635902',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L79:}
    'alipayPublicKey':'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},
    
    '7': {'appId':'2021005127604279',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L85:}
    'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},

    '200': {'appId':'2021006130682365',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L91:}
    'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},

    '2': {'appId':'2021006160693068',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L97:}
    'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'},

    '13': {'appId':'2021006134679030',
    'privateKey': ${CLOUD_MEMBER_LOCAL_PRIVATEKEY_L103:}
    'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
    'signVeriKey':'CLOUD_SECRET_REQUIRED',
    'decryptKey':'CLOUD_SECRET_REQUIRED'}

    }"

wecom:
  corpId: ww33bef5c6db3b679d
  token: ${CLOUD_MEMBER_LOCAL_TOKEN_L112:}
  encodingAESKey: ${CLOUD_MEMBER_LOCAL_ENCODINGAESKEY_L113:}
  corpSecret: ${CLOUD_MEMBER_LOCAL_CORPSECRET_L114:}
alipay:
  apps: "{'10': {'appId':'2021004145680917','privateKey': 'CLOUD_SECRET_REQUIRED',
  'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
  'signVeriKey':'CLOUD_SECRET_REQUIRED',
  'decryptKey':'CLOUD_SECRET_REQUIRED'},
  '9': {'appId':'2021004145680917','privateKey': 'CLOUD_SECRET_REQUIRED',
  'alipayPublicKey': 'CLOUD_SECRET_REQUIRED',
  'signVeriKey':'CLOUD_SECRET_REQUIRED',
  'decryptKey':'CLOUD_SECRET_REQUIRED'}}"




