<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.htyoudao.cloud</groupId>
        <artifactId>youdao</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>youdao-module-version</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>
        version 模块下，主要放app版本管理相关业务。
    </description>
    <modules>
        <module>youdao-module-version-api</module>
        <module>youdao-module-version-biz</module>
    </modules>


</project>
