ALTER TABLE sms_market ADD COLUMN crowd_id VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '人群IDS';
ALTER TABLE coupon_package ADD COLUMN crowd_id VARCHAR(255) NOT NULL DEFAULT '0' COMMENT '人群IDS';
ALTER TABLE `good_coupon` MODIFY COLUMN `version` VARCHAR(255) DEFAULT '0' COMMENT '人群ID';